[window]
opacity = 0.7

[window.padding]
x = 6
y = 6

[font]
size = 14

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[colors.primary]
background = "#2a0e68"
foreground = "#dedede"

[colors.normal]
black = "#15121c"
red = "#cb5760"
green = "#999f63"
yellow = "#d4a067"
blue = "#6c90a8"
magenta = "#776690"
cyan = "#528a9b"
white = "#eeffff"

[colors.bright]
black = "#727480"
red = "#cb5760"
green = "#999f63"
yellow = "#d4a067"
blue = "#6c90a8"
magenta = "#776690"
cyan = "#528a9b"
white = "#eeffff"
